[package]
name = "Blackjack"
version = "0.1.0"
authors = ["Chase Scallion <97cscallion@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
text_io = "0.1.8"